In [542]:
import pandas as pd
import numpy as np
import feather
import matplotlib as mpl
mpl.use('nbAgg')
import matplotlib.pyplot as plt
from sklearn import preprocessing
import sklearn.model_selection as ms
from sklearn import linear_model
import sklearn.metrics as sklm
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import label_binarize
import numpy as np
import numpy.random as nr
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as ss
import math
from sklearn.naive_bayes import GaussianNB, BernoulliNB
%matplotlib inline

In [543]:
pingfInfoFilePath = './dv_personas_190411_previo_linear_regression'
dv_personas_190411_model = pd.read_feather(pingfInfoFilePath,columns=None, use_threads=True)
dv_personas_190411_model.head()

sexo             tipo_acceso tipo_erasmus  edad_fin_primera_titulacion  \
0    M            Selectividad      Ninguno                           23   
1    M            Selectividad      Ninguno                           22   
2    M            Selectividad      Ninguno                           21   
3    M   Formación Profesional      Ninguno                           24   
4    M  Acceso a Segundo Ciclo      Ninguno                           26   

   tto_pcto_dias_trabajados  \
0                      13.0   
1                      65.0   
2                      23.0   
3                      41.0   
4                      41.0   

                                                 dni  \
0  000b4ece399af8f6c90ad84acccc1aaea09d88ea83ac1c...   
1  000e88e4e0244e5317dc105c2f77fdfde83fa66a60c813...   
2  0013670b45b4207d01539bc1d057daa03bab0e2de19916...   
3  001d295ef6bbd65b0fb84c496ff81d6e9f2381e819289b...   
4  00230081e3257d2dd7d77d7722ce78b85545135946ed2e...   

   Titulacion_is_GRADO EN EDUCACIÓN PRIMARIA  \
0                                          0   
1                                          0   
2                                          1   
3                                          0   
4                                          0   

   Titulacion_is_ING. TÉC. OBRAS PÚB. (ESPECIALIDAD EN CONST. CIV.)  \
0                                                  0                  
1                                                  0                  
2                                                  0                  
3                                                  0                  
4                                                  0                  

   Titulacion_is_INGENIERO QUÍMICO  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO FORESTAL (ESPECIALIDAD EN EXPLOTACIONES FORESTALES)  \
0                                                  0                                     
1                                                  0                                     
2                                                  0                                     
3                                                  0                                     
4                                                  0                                     

   ...  Titulacion_is_MÁSTER UNIVERSITARIO EN INVESTIGACIÓN EN HUMANIDADES  \
0  ...                                                  0                    
1  ...                                                  0                    
2  ...                                                  0                    
3  ...                                                  0                    
4  ...                                                  0                    

   Titulacion_is_MÁSTER EN GESTIÓN DEL CONOCIMIENTO BIOMÉDICO E INVESTIGACIÓN CLÍNICA.  \
0                                                  0                                     
1                                                  0                                     
2                                                  0                                     
3                                                  0                                     
4                                                  0                                     

   Titulacion_is_MÁSTER EN GESTIÓN Y DIRECCIÓN HOSTELERA  \
0                                                  0       
1                                                  0       
2                                                  0       
3                                                  0       
4                                                  0       

   Titulacion_is_MÁSTER UNIVERSITARIO EN FORMACIÓN DEL PROFESORADO Y TIC  \
0                                                  0                       
1           

In [544]:
categoricalCols = ['sexo','tipo_acceso','tipo_erasmus']

In [545]:
dv_personas_190411_model_one_hot = pd.get_dummies(data=dv_personas_190411_model,columns=categoricalCols)

In [546]:
dv_personas_190411_model_one_hot.head()

edad_fin_primera_titulacion  tto_pcto_dias_trabajados  \
0                           23                      13.0   
1                           22                      65.0   
2                           21                      23.0   
3                           24                      41.0   
4                           26                      41.0   

                                                 dni  \
0  000b4ece399af8f6c90ad84acccc1aaea09d88ea83ac1c...   
1  000e88e4e0244e5317dc105c2f77fdfde83fa66a60c813...   
2  0013670b45b4207d01539bc1d057daa03bab0e2de19916...   
3  001d295ef6bbd65b0fb84c496ff81d6e9f2381e819289b...   
4  00230081e3257d2dd7d77d7722ce78b85545135946ed2e...   

   Titulacion_is_GRADO EN EDUCACIÓN PRIMARIA  \
0                                          0   
1                                          0   
2                                          1   
3                                          0   
4                                          0   

   Titulacion_is_ING. TÉC. OBRAS PÚB. (ESPECIALIDAD EN CONST. CIV.)  \
0                                                  0                  
1                                                  0                  
2                                                  0                  
3                                                  0                  
4                                                  0                  

   Titulacion_is_INGENIERO QUÍMICO  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO FORESTAL (ESPECIALIDAD EN EXPLOTACIONES FORESTALES)  \
0                                                  0                                     
1                                                  0                                     
2                                                  0                                     
3                                                  0                                     
4                                                  0                                     

   Titulacion_is_GRADO EN MEDICINA  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO INDUSTRIAL (ESPECIALIDAD EN ELECTRICIDAD)  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   Titulacion_is_DIPLOMADO EN ENFERMERÍA  ...  \
0                                      1  ...   
1                                      0  ...   
2                                      0  ...   
3                                      0  ...   
4                                      0  ...   

   tipo_acceso_Estudios universitarios extranjeros parcialmente convalidados  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   tipo_acceso_Formación Profesional  tipo_acceso_Mayores de 25/40/45 años  \
0                                  0                                     0   
1                                  0                                     0   
2                                  0                                     0   
3                    

In [547]:
dv_personas_190411_model_one_hot.drop(['dni'],axis=1,inplace = True)

#### Comenzamos dividiendo el tto_pcto_dias_trabajados en bloques de 25

In [454]:
dv_personas_190411_model_one_hot[dv_personas_190411_model_one_hot['tto_pcto_dias_trabajados'] == 0]

edad_fin_primera_titulacion  tto_pcto_dias_trabajados  \
14                              21                       0.0   
37                              32                       0.0   
88                              21                       0.0   
128                             23                       0.0   
176                             29                       0.0   
...                            ...                       ...   
14536                           21                       0.0   
14618                           37                       0.0   
14677                           38                       0.0   
14691                           27                       0.0   
14701                           21                       0.0   

       Titulacion_is_GRADO EN EDUCACIÓN PRIMARIA  \
14                                             0   
37                                             0   
88                                             1   
128                                            0   
176                                            0   
...                                          ...   
14536                                          0   
14618                                          0   
14677                                          0   
14691                                          0   
14701                                          0   

       Titulacion_is_ING. TÉC. OBRAS PÚB. (ESPECIALIDAD EN CONST. CIV.)  \
14                                                     0                  
37                                                     0                  
88                                                     0                  
128                                                    0                  
176                                                    0                  
...                                                  ...                  
14536                                                  0                  
14618                                                  0                  
14677                                                  0                  
14691                                                  0                  
14701                                                  0                  

       Titulacion_is_INGENIERO QUÍMICO  \
14                                   0   
37                                   0   
88                                   0   
128                                  0   
176                                  0   
...                                ...   
14536                                0   
14618                                0   
14677                                0   
14691                                0   
14701                                0   

       Titulacion_is_INGENIERO TÉCNICO FORESTAL (ESPECIALIDAD EN EXPLOTACIONES FORESTALES)  \
14                                                     0                                     
37                                                     0                                     
88                                                     0                                     
128                                                    0                                     
176                                                    0                                     
...                                                  ...                                     
14536                                                  0                                     
14618                                                  0                                     
14677                                                  0                                     
14691                                                  0                                     
14701                                                  0                                     

       Titulacion_is_GRADO EN MEDICINA  \
14                                  

In [455]:
tto_pcto_dias_trabajados_bucket_array = np.linspace(0,100,5)
tto_pcto_dias_trabajados_bucket_array

array([  0.,  25.,  50.,  75., 100.])

In [456]:
dv_personas_190411_model_one_hot_25 = dv_personas_190411_model_one_hot.copy()
dv_personas_190411_model_one_hot_25['tto_pcto_dias_trabajados'] = pd.cut(dv_personas_190411_model_one_hot_25['tto_pcto_dias_trabajados'],tto_pcto_dias_trabajados_bucket_array,include_lowest=True)
dv_personas_190411_model_one_hot_25.head()

edad_fin_primera_titulacion tto_pcto_dias_trabajados  \
0                           23           (-0.001, 25.0]   
1                           22             (50.0, 75.0]   
2                           21           (-0.001, 25.0]   
3                           24             (25.0, 50.0]   
4                           26             (25.0, 50.0]   

   Titulacion_is_GRADO EN EDUCACIÓN PRIMARIA  \
0                                          0   
1                                          0   
2                                          1   
3                                          0   
4                                          0   

   Titulacion_is_ING. TÉC. OBRAS PÚB. (ESPECIALIDAD EN CONST. CIV.)  \
0                                                  0                  
1                                                  0                  
2                                                  0                  
3                                                  0                  
4                                                  0                  

   Titulacion_is_INGENIERO QUÍMICO  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO FORESTAL (ESPECIALIDAD EN EXPLOTACIONES FORESTALES)  \
0                                                  0                                     
1                                                  0                                     
2                                                  0                                     
3                                                  0                                     
4                                                  0                                     

   Titulacion_is_GRADO EN MEDICINA  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO INDUSTRIAL (ESPECIALIDAD EN ELECTRICIDAD)  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   Titulacion_is_DIPLOMADO EN ENFERMERÍA  \
0                                      1   
1                                      0   
2                                      0   
3                                      0   
4                                      0   

   Titulacion_is_DIPLOMADO EN TERAPIA OCUPACIONAL  ...  \
0                                               0  ...   
1                                               0  ...   
2                                               0  ...   
3                                               0  ...   
4                                               0  ...   

   tipo_acceso_Estudios universitarios extranjeros parcialmente convalidados  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   tipo_acceso_Formación Profesional  tipo_acceso_Mayores de 25/40/45 años  \
0                                  0                                     0   
1                                  0                                     0   
2                                  0                                     0   
3                                  1         

In [457]:
dv_personas_190411_model_one_hot_25['tto_pcto_dias_trabajados'].astype('category')

0        (-0.001, 25.0]
1          (50.0, 75.0]
2        (-0.001, 25.0]
3          (25.0, 50.0]
4          (25.0, 50.0]
              ...      
14710    (-0.001, 25.0]
14711    (-0.001, 25.0]
14712    (-0.001, 25.0]
14713    (-0.001, 25.0]
14714    (-0.001, 25.0]
Name: tto_pcto_dias_trabajados, Length: 14715, dtype: category
Categories (4, interval[float64]): [(-0.001, 25.0] < (25.0, 50.0] < (50.0, 75.0] < (75.0, 100.0]]

In [458]:
dv_personas_190411_model_one_hot_25['tto_pcto_dias_trabajados'] = dv_personas_190411_model_one_hot_25.tto_pcto_dias_trabajados.cat.codes
dv_personas_190411_model_one_hot_25.head()

edad_fin_primera_titulacion  tto_pcto_dias_trabajados  \
0                           23                         0   
1                           22                         2   
2                           21                         0   
3                           24                         1   
4                           26                         1   

   Titulacion_is_GRADO EN EDUCACIÓN PRIMARIA  \
0                                          0   
1                                          0   
2                                          1   
3                                          0   
4                                          0   

   Titulacion_is_ING. TÉC. OBRAS PÚB. (ESPECIALIDAD EN CONST. CIV.)  \
0                                                  0                  
1                                                  0                  
2                                                  0                  
3                                                  0                  
4                                                  0                  

   Titulacion_is_INGENIERO QUÍMICO  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO FORESTAL (ESPECIALIDAD EN EXPLOTACIONES FORESTALES)  \
0                                                  0                                     
1                                                  0                                     
2                                                  0                                     
3                                                  0                                     
4                                                  0                                     

   Titulacion_is_GRADO EN MEDICINA  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO INDUSTRIAL (ESPECIALIDAD EN ELECTRICIDAD)  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   Titulacion_is_DIPLOMADO EN ENFERMERÍA  \
0                                      1   
1                                      0   
2                                      0   
3                                      0   
4                                      0   

   Titulacion_is_DIPLOMADO EN TERAPIA OCUPACIONAL  ...  \
0                                               0  ...   
1                                               0  ...   
2                                               0  ...   
3                                               0  ...   
4                                               0  ...   

   tipo_acceso_Estudios universitarios extranjeros parcialmente convalidados  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   tipo_acceso_Formación Profesional  tipo_acceso_Mayores de 25/40/45 años  \
0                                  0                                     0   
1                                  0                                     0   
2                                  0                                     0   
3                                  1   

In [459]:
dv_personas_190411_model_one_hot_25['tto_pcto_dias_trabajados'].value_counts()

0    7712
1    4452
2    2009
3     542
Name: tto_pcto_dias_trabajados, dtype: int64

In [460]:
Features_1_2 = dv_personas_190411_model_one_hot_25.iloc[:,0:1]
Features_2_2 = dv_personas_190411_model_one_hot_25.iloc[:,2:]
Labels = dv_personas_190411_model_one_hot_25['tto_pcto_dias_trabajados']

In [461]:
Features = np.array(Features_1_2)
Features = np.concatenate([Features, np.array(Features_2_2)], axis = 1)
Features[:2,:]

array([[23,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0],
       [22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       

In [462]:
Features.shape

(14715, 204)

Procedemos a eliminar la característica de "edad_fin_primera_titulacion" para poder aplicar Bernoulli Nave Bayes, que sólo funciona con variables binarias

In [463]:
Features = Features[:,1:]
Features[:2,:]

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 

In [464]:
Features.shape

(14715, 203)

In [465]:
Labels = np.array(Labels)
Labels[:20]

array([0, 2, 0, 1, 1, 0, 0, 3, 0, 1, 2, 3, 0, 0, 0, 1, 0, 1, 3, 0],
      dtype=int8)

In [466]:
nr.seed(123)
inside = ms.KFold(n_splits=10, shuffle = True)
nr.seed(321)
outside = ms.KFold(n_splits=10, shuffle = True)

In [467]:
nr.seed(3456)
## Define the dictionary for the grid search and the model object to search on
param_grid = {"alpha": [0.0001, 0.001, 0.01, 0.1, 1, 10]}
## Define the NB regression model
NB_clf_ovo_25 = BernoulliNB() 

## Perform the grid search over the parameters
clf_ovo_25 = ms.GridSearchCV(estimator = NB_clf_ovo_25, param_grid = param_grid, 
                      cv = inside, # Use the inside folds
                      scoring = 'roc_auc_ovo_weighted',
                      return_train_score = True)
clf_ovo_25.fit(Features, Labels)
print(clf_ovo_25.best_estimator_.alpha)

0.1


In [468]:
nr.seed(498)
cv_estimate = ms.cross_val_score(clf_ovo_25, Features, Labels, 
                                 cv = outside) # Use the outside folds

print('Mean performance metric = %4.3f' % np.mean(cv_estimate))
print('SDT of the metric       = %4.3f' % np.std(cv_estimate))
print('Outcomes by cv fold')
for i, x in enumerate(cv_estimate):
    print('Fold %2d    %4.3f' % (i+1, x))

Mean performance metric = 0.642
SDT of the metric       = 0.009
Outcomes by cv fold
Fold  1    0.643
Fold  2    0.654
Fold  3    0.636
Fold  4    0.642
Fold  5    0.632
Fold  6    0.637
Fold  7    0.650
Fold  8    0.651
Fold  9    0.649
Fold 10    0.627


In [469]:
nr.seed(9988)
indx = range(Features.shape[0])
indx = ms.train_test_split(indx, test_size = 3679)
x_train = Features[indx[0],:]
y_train = np.ravel(Labels[indx[0]])
x_test = Features[indx[1],:]
y_test = np.ravel(Labels[indx[1]])

In [470]:
NB_mod_ovo_25 = BernoulliNB(alpha=clf_ovo_25.best_estimator_.alpha)
NB_mod_ovo_25.fit(x_train, y_train)
scores = NB_mod_ovo_25.predict(x_test)
scores

array([1, 2, 0, ..., 3, 0, 0], dtype=int8)

In [471]:
def print_metrics_25(labels, scores):
    conf = sklm.confusion_matrix(labels, scores)
    print('                 Confusion matrix')
    print('                 Score [0,25]    Score (25,50] Score (50,75] Score (75,100]')
    print('Actual [0,25]     %6d' % conf[0,0] + '             %5d' % conf[0,1] + '             %5d' % conf[0,2] + '              %5d' % conf[0,3])
    print('Actual (25,50]    %6d' % conf[1,0] + '             %5d' % conf[1,1] + '             %5d' % conf[1,2] + '              %5d' % conf[1,3])
    print('Actual (50,75]    %6d' % conf[2,0] + '             %5d' % conf[2,1] + '             %5d' % conf[2,2] + '              %5d' % conf[2,3])
    print('Actual (75,100]   %6d' % conf[3,0] + '             %5d' % conf[3,1] + '             %5d' % conf[3,2] + '              %5d' % conf[3,3])

    print('')
    print('Accuracy        %0.2f' % sklm.accuracy_score(labels, scores))
    metrics = sklm.precision_recall_fscore_support(labels, scores)
    print(' ')
    print('          Score [0,25]  Score (25,50]  Score (50,75] Score (75,100]')
    print('Num case   %0.2f' % metrics[3][0] + '     %0.2f' % metrics[3][1] + '      %0.2f' % metrics[3][2] + '      %0.2f' % metrics[3][3] )
    print('Precision   %0.2f' % metrics[0][0] + '      %0.2f' % metrics[0][1] + '       %0.2f' % metrics[0][2] + '     %0.2f' % metrics[0][3] )
    print('Recall      %0.2f' % metrics[1][0] + '      %0.2f' % metrics[1][1] + '       %0.2f' % metrics[1][2] + '     %0.2f' % metrics[1][3] )
    print('F1          %0.2f' % metrics[2][0] + '      %0.2f' % metrics[2][1] + '       %0.2f' % metrics[2][2] + '     %0.2f' % metrics[2][3] )

In [472]:
print_metrics_25(y_test, scores)  

                 Confusion matrix
                 Score [0,25]    Score (25,50] Score (50,75] Score (75,100]
Actual [0,25]       1642               160               108                 26
Actual (25,50]       830               167                92                 18
Actual (50,75]       337                57                83                 19
Actual (75,100]       90                12                31                  7

Accuracy        0.52
 
          Score [0,25]  Score (25,50]  Score (50,75] Score (75,100]
Num case   1936.00     1107.00      496.00      140.00
Precision   0.57      0.42       0.26     0.10
Recall      0.85      0.15       0.17     0.05
F1          0.68      0.22       0.20     0.07


In [473]:
nr.seed(3456)
## Define the dictionary for the grid search and the model object to search on
param_grid = {"alpha": [0.0001, 0.001, 0.01, 0.1, 1, 10]}
## Define the NB regression model
NB_clf_ovr_25 = BernoulliNB() 

## Perform the grid search over the parameters
clf_ovr_25 = ms.GridSearchCV(estimator = NB_clf_ovr_25, param_grid = param_grid, 
                      cv = inside, # Use the inside folds
                      scoring = 'roc_auc_ovr_weighted',
                      return_train_score = True)
clf_ovr_25.fit(Features, Labels)
print(clf_ovr_25.best_estimator_.alpha)

0.1


In [474]:
nr.seed(498)
cv_estimate = ms.cross_val_score(clf_ovr_25, Features, Labels, 
                                 cv = outside) # Use the outside folds

print('Mean performance metric = %4.3f' % np.mean(cv_estimate))
print('SDT of the metric       = %4.3f' % np.std(cv_estimate))
print('Outcomes by cv fold')
for i, x in enumerate(cv_estimate):
    print('Fold %2d    %4.3f' % (i+1, x))

Mean performance metric = 0.615
SDT of the metric       = 0.006
Outcomes by cv fold
Fold  1    0.621
Fold  2    0.617
Fold  3    0.615
Fold  4    0.608
Fold  5    0.602
Fold  6    0.610
Fold  7    0.617
Fold  8    0.621
Fold  9    0.621
Fold 10    0.615


In [475]:
nr.seed(9988)
indx = range(Features.shape[0])
indx = ms.train_test_split(indx, test_size = 3679)
x_train = Features[indx[0],:]
y_train = np.ravel(Labels[indx[0]])
x_test = Features[indx[1],:]
y_test = np.ravel(Labels[indx[1]])

In [476]:
NB_mod_ovr_25 = BernoulliNB(alpha=clf_ovr_25.best_estimator_.alpha)
NB_mod_ovr_25.fit(x_train, y_train)
scores = NB_mod_ovr_25.predict(x_test)
scores

array([1, 2, 0, ..., 3, 0, 0], dtype=int8)

In [477]:
print_metrics_25(y_test, scores)  

                 Confusion matrix
                 Score [0,25]    Score (25,50] Score (50,75] Score (75,100]
Actual [0,25]       1642               160               108                 26
Actual (25,50]       830               167                92                 18
Actual (50,75]       337                57                83                 19
Actual (75,100]       90                12                31                  7

Accuracy        0.52
 
          Score [0,25]  Score (25,50]  Score (50,75] Score (75,100]
Num case   1936.00     1107.00      496.00      140.00
Precision   0.57      0.42       0.26     0.10
Recall      0.85      0.15       0.17     0.05
F1          0.68      0.22       0.20     0.07


#### Procedemos a dividir el tto_pcto_dias_trabajados en bloques de 20

In [478]:
tto_pcto_dias_trabajados_bucket_array = np.linspace(0,100,6)
tto_pcto_dias_trabajados_bucket_array

array([  0.,  20.,  40.,  60.,  80., 100.])

In [479]:
dv_personas_190411_model_one_hot_20 = dv_personas_190411_model_one_hot.copy()
dv_personas_190411_model_one_hot_20['tto_pcto_dias_trabajados'] = pd.cut(dv_personas_190411_model_one_hot_20['tto_pcto_dias_trabajados'],tto_pcto_dias_trabajados_bucket_array,include_lowest=True)
dv_personas_190411_model_one_hot_20.head()

edad_fin_primera_titulacion tto_pcto_dias_trabajados  \
0                           23           (-0.001, 20.0]   
1                           22             (60.0, 80.0]   
2                           21             (20.0, 40.0]   
3                           24             (40.0, 60.0]   
4                           26             (40.0, 60.0]   

   Titulacion_is_GRADO EN EDUCACIÓN PRIMARIA  \
0                                          0   
1                                          0   
2                                          1   
3                                          0   
4                                          0   

   Titulacion_is_ING. TÉC. OBRAS PÚB. (ESPECIALIDAD EN CONST. CIV.)  \
0                                                  0                  
1                                                  0                  
2                                                  0                  
3                                                  0                  
4                                                  0                  

   Titulacion_is_INGENIERO QUÍMICO  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO FORESTAL (ESPECIALIDAD EN EXPLOTACIONES FORESTALES)  \
0                                                  0                                     
1                                                  0                                     
2                                                  0                                     
3                                                  0                                     
4                                                  0                                     

   Titulacion_is_GRADO EN MEDICINA  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO INDUSTRIAL (ESPECIALIDAD EN ELECTRICIDAD)  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   Titulacion_is_DIPLOMADO EN ENFERMERÍA  \
0                                      1   
1                                      0   
2                                      0   
3                                      0   
4                                      0   

   Titulacion_is_DIPLOMADO EN TERAPIA OCUPACIONAL  ...  \
0                                               0  ...   
1                                               0  ...   
2                                               0  ...   
3                                               0  ...   
4                                               0  ...   

   tipo_acceso_Estudios universitarios extranjeros parcialmente convalidados  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   tipo_acceso_Formación Profesional  tipo_acceso_Mayores de 25/40/45 años  \
0                                  0                                     0   
1                                  0                                     0   
2                                  0                                     0   
3                                  1         

In [480]:
dv_personas_190411_model_one_hot_20['tto_pcto_dias_trabajados'].astype('category')

0        (-0.001, 20.0]
1          (60.0, 80.0]
2          (20.0, 40.0]
3          (40.0, 60.0]
4          (40.0, 60.0]
              ...      
14710    (-0.001, 20.0]
14711    (-0.001, 20.0]
14712    (-0.001, 20.0]
14713      (20.0, 40.0]
14714    (-0.001, 20.0]
Name: tto_pcto_dias_trabajados, Length: 14715, dtype: category
Categories (5, interval[float64]): [(-0.001, 20.0] < (20.0, 40.0] < (40.0, 60.0] < (60.0, 80.0] < (80.0, 100.0]]

In [481]:
dv_personas_190411_model_one_hot_20['tto_pcto_dias_trabajados'] = dv_personas_190411_model_one_hot_20.tto_pcto_dias_trabajados.cat.codes
dv_personas_190411_model_one_hot_20.head()

edad_fin_primera_titulacion  tto_pcto_dias_trabajados  \
0                           23                         0   
1                           22                         3   
2                           21                         1   
3                           24                         2   
4                           26                         2   

   Titulacion_is_GRADO EN EDUCACIÓN PRIMARIA  \
0                                          0   
1                                          0   
2                                          1   
3                                          0   
4                                          0   

   Titulacion_is_ING. TÉC. OBRAS PÚB. (ESPECIALIDAD EN CONST. CIV.)  \
0                                                  0                  
1                                                  0                  
2                                                  0                  
3                                                  0                  
4                                                  0                  

   Titulacion_is_INGENIERO QUÍMICO  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO FORESTAL (ESPECIALIDAD EN EXPLOTACIONES FORESTALES)  \
0                                                  0                                     
1                                                  0                                     
2                                                  0                                     
3                                                  0                                     
4                                                  0                                     

   Titulacion_is_GRADO EN MEDICINA  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO INDUSTRIAL (ESPECIALIDAD EN ELECTRICIDAD)  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   Titulacion_is_DIPLOMADO EN ENFERMERÍA  \
0                                      1   
1                                      0   
2                                      0   
3                                      0   
4                                      0   

   Titulacion_is_DIPLOMADO EN TERAPIA OCUPACIONAL  ...  \
0                                               0  ...   
1                                               0  ...   
2                                               0  ...   
3                                               0  ...   
4                                               0  ...   

   tipo_acceso_Estudios universitarios extranjeros parcialmente convalidados  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   tipo_acceso_Formación Profesional  tipo_acceso_Mayores de 25/40/45 años  \
0                                  0                                     0   
1                                  0                                     0   
2                                  0                                     0   
3                                  1   

In [482]:
dv_personas_190411_model_one_hot_20['tto_pcto_dias_trabajados'].value_counts()

0    6377
1    4373
2    2440
3    1147
4     378
Name: tto_pcto_dias_trabajados, dtype: int64

In [483]:
Features_1_2 = dv_personas_190411_model_one_hot_20.iloc[:,0:1]
Features_2_2 = dv_personas_190411_model_one_hot_20.iloc[:,2:]
Labels = dv_personas_190411_model_one_hot_20['tto_pcto_dias_trabajados']

In [484]:
Features = np.array(Features_1_2)
Features = np.concatenate([Features, np.array(Features_2_2)], axis = 1)
Features[:2,:]

array([[23,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0],
       [22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       

In [485]:
Features.shape

(14715, 204)

Procedemos a eliminar la característica de "edad_fin_primera_titulacion" para poder aplicar Bernoulli Nave Bayes, que sólo funciona con variables binarias

In [486]:
Features = Features[:,1:]
Features[:2,:]

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 

In [487]:
Features.shape

(14715, 203)

In [488]:
Labels = np.array(Labels)
Labels[:20]

array([0, 3, 1, 2, 2, 0, 0, 3, 0, 2, 3, 4, 0, 0, 0, 1, 0, 1, 3, 0],
      dtype=int8)

In [489]:
nr.seed(123)
inside = ms.KFold(n_splits=10, shuffle = True)
nr.seed(321)
outside = ms.KFold(n_splits=10, shuffle = True)

In [490]:
nr.seed(3456)
## Define the dictionary for the grid search and the model object to search on
param_grid = {"alpha": [0.0001, 0.001, 0.01, 0.1, 1, 10]}
## Define the NB regression model
NB_clf_ovo_20 = BernoulliNB() 

## Perform the grid search over the parameters
clf_ovo_20 = ms.GridSearchCV(estimator = NB_clf_ovo_20, param_grid = param_grid, 
                      cv = inside, # Use the inside folds
                      scoring = 'roc_auc_ovo_weighted',
                      return_train_score = True)
clf_ovo_20.fit(Features, Labels)
print(clf_ovo_20.best_estimator_.alpha)

1


In [491]:
nr.seed(498)
cv_estimate = ms.cross_val_score(clf_ovo_20, Features, Labels, 
                                 cv = outside) # Use the outside folds

print('Mean performance metric = %4.3f' % np.mean(cv_estimate))
print('SDT of the metric       = %4.3f' % np.std(cv_estimate))
print('Outcomes by cv fold')
for i, x in enumerate(cv_estimate):
    print('Fold %2d    %4.3f' % (i+1, x))

Mean performance metric = 0.631
SDT of the metric       = 0.010
Outcomes by cv fold
Fold  1    0.631
Fold  2    0.651
Fold  3    0.626
Fold  4    0.632
Fold  5    0.620
Fold  6    0.628
Fold  7    0.619
Fold  8    0.635
Fold  9    0.645
Fold 10    0.625


In [492]:
nr.seed(9988)
indx = range(Features.shape[0])
indx = ms.train_test_split(indx, test_size = 3679)
x_train = Features[indx[0],:]
y_train = np.ravel(Labels[indx[0]])
x_test = Features[indx[1],:]
y_test = np.ravel(Labels[indx[1]])

In [493]:
NB_mod_ovo_20 = BernoulliNB(alpha=clf_ovo_20.best_estimator_.alpha)
NB_mod_ovo_20.fit(x_train, y_train)
scores = NB_mod_ovo_20.predict(x_test)
scores

array([1, 3, 0, ..., 3, 0, 0], dtype=int8)

In [494]:
def print_metrics_20(labels, scores):
    conf = sklm.confusion_matrix(labels, scores)
    print('                 Confusion matrix')
    print('                 Score [0,20]    Score (20,40] Score (40,60] Score (60,80] Score (80,100]')
    print('Actual [0,20]     %6d' % conf[0,0] + '             %5d' % conf[0,1] + '             %5d' % conf[0,2] + '              %5d' % conf[0,3] + '              %5d' % conf[0,4])
    print('Actual (20,40]   %6d' % conf[1,0] + '             %5d' % conf[1,1] + '             %5d' % conf[1,2] + '              %5d' % conf[1,3] + '              %5d' % conf[1,4])
    print('Actual (40,60]   %6d' % conf[2,0] + '             %5d' % conf[2,1] + '             %5d' % conf[2,2] + '              %5d' % conf[2,3] + '              %5d' % conf[2,4])
    print('Actual (60,80]   %6d' % conf[3,0] + '             %5d' % conf[3,1] + '             %5d' % conf[3,2] + '              %5d' % conf[3,3] + '              %5d' % conf[3,4])
    print('Actual (80,100]  %6d' % conf[4,0] + '             %5d' % conf[4,1] + '             %5d' % conf[4,2] + '              %5d' % conf[4,3] + '              %5d' % conf[4,4])

    print('')
    print('Accuracy        %0.2f' % sklm.accuracy_score(labels, scores))
    metrics = sklm.precision_recall_fscore_support(labels, scores)
    print(' ')
    print('          Score [0,25]  Score (25,50]  Score (50,75] Score (75,100]')
    print('Num case   %0.2f' % metrics[3][0] + '     %0.2f' % metrics[3][1] + '      %0.2f' % metrics[3][2] + '      %0.2f' % metrics[3][3] + '       %0.2f' % metrics[3][4])
    print('Precision   %0.2f' % metrics[0][0] + '      %0.2f' % metrics[0][1] + '       %0.2f' % metrics[0][2] + '     %0.2f' % metrics[0][3] + '     %0.2f' % metrics[0][4])
    print('Recall      %0.2f' % metrics[1][0] + '      %0.2f' % metrics[1][1] + '       %0.2f' % metrics[1][2] + '     %0.2f' % metrics[1][3] + '     %0.2f' % metrics[1][4])
    print('F1          %0.2f' % metrics[2][0] + '      %0.2f' % metrics[2][1] + '       %0.2f' % metrics[2][2] + '     %0.2f' % metrics[2][3] + '     %0.2f' % metrics[2][4])

In [495]:
print_metrics_20(y_test, scores)  

                 Confusion matrix
                 Score [0,20]    Score (20,40] Score (40,60] Score (60,80] Score (80,100]
Actual [0,20]       1297               156                76                 56                 11
Actual (20,40]      808               162                75                 47                 15
Actual (40,60]      411                70                66                 37                 15
Actual (60,80]      172                20                35                 41                  8
Actual (80,100]      62                 7                11                 16                  5

Accuracy        0.43
 
          Score [0,25]  Score (25,50]  Score (50,75] Score (75,100]
Num case   1596.00     1107.00      599.00      276.00       101.00
Precision   0.47      0.39       0.25     0.21     0.09
Recall      0.81      0.15       0.11     0.15     0.05
F1          0.60      0.21       0.15     0.17     0.06


In [496]:
nr.seed(3456)
## Define the dictionary for the grid search and the model object to search on
param_grid = {"alpha": [0.0001, 0.001, 0.01, 0.1, 1, 10]}
## Define the NB regression model
NB_clf_ovr_20 = BernoulliNB() 

## Perform the grid search over the parameters
clf_ovr_20 = ms.GridSearchCV(estimator = NB_clf_ovr_20, param_grid = param_grid, 
                      cv = inside, # Use the inside folds
                      scoring = 'roc_auc_ovr_weighted',
                      return_train_score = True)
clf_ovr_20.fit(Features, Labels)
print(clf_ovr_20.best_estimator_.alpha)

1


In [497]:
nr.seed(498)
cv_estimate = ms.cross_val_score(clf_ovr_20, Features, Labels, 
                                 cv = outside) # Use the outside folds

print('Mean performance metric = %4.3f' % np.mean(cv_estimate))
print('SDT of the metric       = %4.3f' % np.std(cv_estimate))
print('Outcomes by cv fold')
for i, x in enumerate(cv_estimate):
    print('Fold %2d    %4.3f' % (i+1, x))

Mean performance metric = 0.602
SDT of the metric       = 0.012
Outcomes by cv fold
Fold  1    0.603
Fold  2    0.614
Fold  3    0.603
Fold  4    0.603
Fold  5    0.580
Fold  6    0.603
Fold  7    0.585
Fold  8    0.601
Fold  9    0.622
Fold 10    0.607


In [498]:
nr.seed(9988)
indx = range(Features.shape[0])
indx = ms.train_test_split(indx, test_size = 3679)
x_train = Features[indx[0],:]
y_train = np.ravel(Labels[indx[0]])
x_test = Features[indx[1],:]
y_test = np.ravel(Labels[indx[1]])

In [499]:
NB_mod_ovr_20 = BernoulliNB(alpha=clf_ovr_20.best_estimator_.alpha)
NB_mod_ovr_20.fit(x_train, y_train)
scores = NB_mod_ovr_20.predict(x_test)
scores

array([1, 3, 0, ..., 3, 0, 0], dtype=int8)

In [500]:
print_metrics_20(y_test, scores)  

                 Confusion matrix
                 Score [0,20]    Score (20,40] Score (40,60] Score (60,80] Score (80,100]
Actual [0,20]       1297               156                76                 56                 11
Actual (20,40]      808               162                75                 47                 15
Actual (40,60]      411                70                66                 37                 15
Actual (60,80]      172                20                35                 41                  8
Actual (80,100]      62                 7                11                 16                  5

Accuracy        0.43
 
          Score [0,25]  Score (25,50]  Score (50,75] Score (75,100]
Num case   1596.00     1107.00      599.00      276.00       101.00
Precision   0.47      0.39       0.25     0.21     0.09
Recall      0.81      0.15       0.11     0.15     0.05
F1          0.60      0.21       0.15     0.17     0.06


#### Procedemos a dividir el tto_pcto_dias_trabajados en bloques de 33

In [501]:
tto_pcto_dias_trabajados_bucket_array = np.linspace(0,100,4)
tto_pcto_dias_trabajados_bucket_array

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [502]:
dv_personas_190411_model_one_hot_33 = dv_personas_190411_model_one_hot.copy()
dv_personas_190411_model_one_hot_33['tto_pcto_dias_trabajados'] = pd.cut(dv_personas_190411_model_one_hot_33['tto_pcto_dias_trabajados'],tto_pcto_dias_trabajados_bucket_array,include_lowest=True)
dv_personas_190411_model_one_hot_33.head()

edad_fin_primera_titulacion tto_pcto_dias_trabajados  \
0                           23         (-0.001, 33.333]   
1                           22         (33.333, 66.667]   
2                           21         (-0.001, 33.333]   
3                           24         (33.333, 66.667]   
4                           26         (33.333, 66.667]   

   Titulacion_is_GRADO EN EDUCACIÓN PRIMARIA  \
0                                          0   
1                                          0   
2                                          1   
3                                          0   
4                                          0   

   Titulacion_is_ING. TÉC. OBRAS PÚB. (ESPECIALIDAD EN CONST. CIV.)  \
0                                                  0                  
1                                                  0                  
2                                                  0                  
3                                                  0                  
4                                                  0                  

   Titulacion_is_INGENIERO QUÍMICO  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO FORESTAL (ESPECIALIDAD EN EXPLOTACIONES FORESTALES)  \
0                                                  0                                     
1                                                  0                                     
2                                                  0                                     
3                                                  0                                     
4                                                  0                                     

   Titulacion_is_GRADO EN MEDICINA  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO INDUSTRIAL (ESPECIALIDAD EN ELECTRICIDAD)  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   Titulacion_is_DIPLOMADO EN ENFERMERÍA  \
0                                      1   
1                                      0   
2                                      0   
3                                      0   
4                                      0   

   Titulacion_is_DIPLOMADO EN TERAPIA OCUPACIONAL  ...  \
0                                               0  ...   
1                                               0  ...   
2                                               0  ...   
3                                               0  ...   
4                                               0  ...   

   tipo_acceso_Estudios universitarios extranjeros parcialmente convalidados  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   tipo_acceso_Formación Profesional  tipo_acceso_Mayores de 25/40/45 años  \
0                                  0                                     0   
1                                  0                                     0   
2                                  0                                     0   
3                                  1         

In [503]:
dv_personas_190411_model_one_hot_33['tto_pcto_dias_trabajados'].astype('category')

0        (-0.001, 33.333]
1        (33.333, 66.667]
2        (-0.001, 33.333]
3        (33.333, 66.667]
4        (33.333, 66.667]
               ...       
14710    (-0.001, 33.333]
14711    (-0.001, 33.333]
14712    (-0.001, 33.333]
14713    (-0.001, 33.333]
14714    (-0.001, 33.333]
Name: tto_pcto_dias_trabajados, Length: 14715, dtype: category
Categories (3, interval[float64]): [(-0.001, 33.333] < (33.333, 66.667] < (66.667, 100.0]]

In [504]:
dv_personas_190411_model_one_hot_33['tto_pcto_dias_trabajados'] = dv_personas_190411_model_one_hot_33.tto_pcto_dias_trabajados.cat.codes
dv_personas_190411_model_one_hot_33.head()

edad_fin_primera_titulacion  tto_pcto_dias_trabajados  \
0                           23                         0   
1                           22                         1   
2                           21                         0   
3                           24                         1   
4                           26                         1   

   Titulacion_is_GRADO EN EDUCACIÓN PRIMARIA  \
0                                          0   
1                                          0   
2                                          1   
3                                          0   
4                                          0   

   Titulacion_is_ING. TÉC. OBRAS PÚB. (ESPECIALIDAD EN CONST. CIV.)  \
0                                                  0                  
1                                                  0                  
2                                                  0                  
3                                                  0                  
4                                                  0                  

   Titulacion_is_INGENIERO QUÍMICO  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO FORESTAL (ESPECIALIDAD EN EXPLOTACIONES FORESTALES)  \
0                                                  0                                     
1                                                  0                                     
2                                                  0                                     
3                                                  0                                     
4                                                  0                                     

   Titulacion_is_GRADO EN MEDICINA  \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   

   Titulacion_is_INGENIERO TÉCNICO INDUSTRIAL (ESPECIALIDAD EN ELECTRICIDAD)  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   Titulacion_is_DIPLOMADO EN ENFERMERÍA  \
0                                      1   
1                                      0   
2                                      0   
3                                      0   
4                                      0   

   Titulacion_is_DIPLOMADO EN TERAPIA OCUPACIONAL  ...  \
0                                               0  ...   
1                                               0  ...   
2                                               0  ...   
3                                               0  ...   
4                                               0  ...   

   tipo_acceso_Estudios universitarios extranjeros parcialmente convalidados  \
0                                                  0                           
1                                                  0                           
2                                                  0                           
3                                                  0                           
4                                                  0                           

   tipo_acceso_Formación Profesional  tipo_acceso_Mayores de 25/40/45 años  \
0                                  0                                     0   
1                                  0                                     0   
2                                  0                                     0   
3                                  1   

In [505]:
dv_personas_190411_model_one_hot_33['tto_pcto_dias_trabajados'].value_counts()

0    9554
1    4121
2    1040
Name: tto_pcto_dias_trabajados, dtype: int64

In [506]:
Features_1_2 = dv_personas_190411_model_one_hot_33.iloc[:,0:1]
Features_2_2 = dv_personas_190411_model_one_hot_33.iloc[:,2:]
Labels = dv_personas_190411_model_one_hot_33['tto_pcto_dias_trabajados']

In [507]:
Features = np.array(Features_1_2)
Features = np.concatenate([Features, np.array(Features_2_2)], axis = 1)
Features[:2,:]

array([[23,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0],
       [22,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       

In [508]:
Features.shape

(14715, 204)

Procedemos a eliminar la característica de "edad_fin_primera_titulacion" para poder aplicar Bernoulli Nave Bayes, que sólo funciona con variables binarias

In [509]:
Features = Features[:,1:]
Features[:2,:]

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 

In [510]:
Features.shape

(14715, 203)

In [511]:
Labels = np.array(Labels)
Labels[:20]

array([0, 1, 0, 1, 1, 0, 0, 2, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0],
      dtype=int8)

In [512]:
nr.seed(123)
inside = ms.KFold(n_splits=10, shuffle = True)
nr.seed(321)
outside = ms.KFold(n_splits=10, shuffle = True)

In [513]:
nr.seed(3456)
## Define the dictionary for the grid search and the model object to search on
param_grid = {"alpha": [0.0001, 0.001, 0.01, 0.1, 1, 10]}
## Define the NB regression model
NB_clf_ovo_33 = BernoulliNB() 

## Perform the grid search over the parameters
clf_ovo_33 = ms.GridSearchCV(estimator = NB_clf_ovo_33, param_grid = param_grid, 
                      cv = inside, # Use the inside folds
                      scoring = 'roc_auc_ovo_weighted',
                      return_train_score = True)
clf_ovo_33.fit(Features, Labels)
print(clf_ovo_33.best_estimator_.alpha)

1


In [514]:
nr.seed(498)
cv_estimate = ms.cross_val_score(clf_ovo_33, Features, Labels, 
                                 cv = outside) # Use the outside folds

print('Mean performance metric = %4.3f' % np.mean(cv_estimate))
print('SDT of the metric       = %4.3f' % np.std(cv_estimate))
print('Outcomes by cv fold')
for i, x in enumerate(cv_estimate):
    print('Fold %2d    %4.3f' % (i+1, x))

Mean performance metric = 0.653
SDT of the metric       = 0.006
Outcomes by cv fold
Fold  1    0.652
Fold  2    0.652
Fold  3    0.646
Fold  4    0.661
Fold  5    0.643
Fold  6    0.658
Fold  7    0.663
Fold  8    0.658
Fold  9    0.654
Fold 10    0.647


In [515]:
nr.seed(9988)
indx = range(Features.shape[0])
indx = ms.train_test_split(indx, test_size = 3679)
x_train = Features[indx[0],:]
y_train = np.ravel(Labels[indx[0]])
x_test = Features[indx[1],:]
y_test = np.ravel(Labels[indx[1]])

In [516]:
NB_mod_ovo_33 = BernoulliNB(alpha=clf_ovo_33.best_estimator_.alpha)
NB_mod_ovo_33.fit(x_train, y_train)
scores = NB_mod_ovo_33.predict(x_test)
scores

array([1, 1, 0, ..., 2, 0, 0], dtype=int8)

In [517]:
def print_metrics_33(labels, scores):
    conf = sklm.confusion_matrix(labels, scores)
    print('                 Confusion matrix')
    print('                 Score [0,333.333]    Score (33.333,66.667] Score (66.667,100]')
    print('Actual [0,333.333]        %6d' % conf[0,0] + '             %5d' % conf[0,1] + '             %5d' % conf[0,2])
    print('Actual (33.333,66.667]    %6d' % conf[1,0] + '             %5d' % conf[1,1] + '             %5d' % conf[1,2])
    print('Actual (66.667,100]       %6d' % conf[2,0] + '             %5d' % conf[2,1] + '             %5d' % conf[2,2])

    print('')
    print('Accuracy        %0.2f' % sklm.accuracy_score(labels, scores))
    metrics = sklm.precision_recall_fscore_support(labels, scores)
    print(' ')
    print('         Score [0,333.333]    Score (33.333,66.667] Score (66.667,100]')
    print('Num case   %0.2f' % metrics[3][0] + '     %0.2f' % metrics[3][1] + '      %0.2f' % metrics[3][2] )
    print('Precision   %0.2f' % metrics[0][0] + '      %0.2f' % metrics[0][1] + '       %0.2f' % metrics[0][2] )
    print('Recall      %0.2f' % metrics[1][0] + '      %0.2f' % metrics[1][1] + '       %0.2f' % metrics[1][2] )
    print('F1          %0.2f' % metrics[2][0] + '      %0.2f' % metrics[2][1] + '       %0.2f' % metrics[2][2] )

In [518]:
print_metrics_33(y_test, scores)  

                 Confusion matrix
                 Score [0,333.333]    Score (33.333,66.667] Score (66.667,100]
Actual [0,333.333]          2100               186                85
Actual (33.333,66.667]       794               191                65
Actual (66.667,100]          178                40                40

Accuracy        0.63
 
         Score [0,333.333]    Score (33.333,66.667] Score (66.667,100]
Num case   2371.00     1050.00      258.00
Precision   0.68      0.46       0.21
Recall      0.89      0.18       0.16
F1          0.77      0.26       0.18


In [519]:
nr.seed(3456)
## Define the dictionary for the grid search and the model object to search on
param_grid = {"alpha": [0.0001, 0.001, 0.01, 0.1, 1, 10]}
## Define the NB regression model
NB_clf_ovr_33 = BernoulliNB() 

## Perform the grid search over the parameters
clf_ovr_33 = ms.GridSearchCV(estimator = NB_clf_ovr_33, param_grid = param_grid, 
                      cv = inside, # Use the inside folds
                      scoring = 'roc_auc_ovr_weighted',
                      return_train_score = True)
clf_ovr_33.fit(Features, Labels)
print(clf_ovr_33.best_estimator_.alpha)

0.1


In [520]:
nr.seed(498)
cv_estimate = ms.cross_val_score(clf_ovr_33, Features, Labels, 
                                 cv = outside) # Use the outside folds

print('Mean performance metric = %4.3f' % np.mean(cv_estimate))
print('SDT of the metric       = %4.3f' % np.std(cv_estimate))
print('Outcomes by cv fold')
for i, x in enumerate(cv_estimate):
    print('Fold %2d    %4.3f' % (i+1, x))

Mean performance metric = 0.641
SDT of the metric       = 0.009
Outcomes by cv fold
Fold  1    0.637
Fold  2    0.626
Fold  3    0.637
Fold  4    0.645
Fold  5    0.628
Fold  6    0.641
Fold  7    0.643
Fold  8    0.651
Fold  9    0.645
Fold 10    0.654


In [521]:
nr.seed(9988)
indx = range(Features.shape[0])
indx = ms.train_test_split(indx, test_size = 3679)
x_train = Features[indx[0],:]
y_train = np.ravel(Labels[indx[0]])
x_test = Features[indx[1],:]
y_test = np.ravel(Labels[indx[1]])

In [522]:
NB_mod_ovr_33 = BernoulliNB(alpha=clf_ovr_33.best_estimator_.alpha)
NB_mod_ovr_33.fit(x_train, y_train)
scores = NB_mod_ovr_33.predict(x_test)
scores

array([1, 1, 0, ..., 2, 0, 0], dtype=int8)

In [523]:
print_metrics_33(y_test, scores)  

                 Confusion matrix
                 Score [0,333.333]    Score (33.333,66.667] Score (66.667,100]
Actual [0,333.333]          2095               180                96
Actual (33.333,66.667]       796               178                76
Actual (66.667,100]          178                34                46

Accuracy        0.63
 
         Score [0,333.333]    Score (33.333,66.667] Score (66.667,100]
Num case   2371.00     1050.00      258.00
Precision   0.68      0.45       0.21
Recall      0.88      0.17       0.18
F1          0.77      0.25       0.19
